# Based on the following resources:
# - https://vite.dev/guide/static-deploy#github-pages
# - https://pnpm.io/continuous-integration#github-actions
# - https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/

on:
  push:
    branches: ['main']

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies and build site
        run: pnpm install && pnpm build

      - name: Publish site
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name='dev-syabilyusoff-com'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
